# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
       - main
    paths:
       - 'dbscripts/deploy/**'
 # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
# note the below assumes that a host path or volume is mounted into the container at ./Docker (or action will fail) !!!
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL }} --changeLogFile=/dbscripts/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} status 
    
    - name: Run 'Liquibase update sql' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL}} --changeLogFile=/dbscripts/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --logLevel=debug updateSQL
        
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL}} --changeLogFile=/dbscripts/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --logLevel=debug update
